name: cartoonify
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.8
  - cmake==3.21.1
  - onnxruntime==1.10.0
  - torchvision==0.9.0
  - numpy==1.19.2
  - ipython==7.21.0
  - opencv-python-headless
  - dlib
