name: cartoonify
channels:
  - conda-forge
dependencies:
  - python==3.8
  - cmake==3.21.1
  - torch==1.8.0
  - torchvision==0.9.0
  - numpy==1.19.2
  - ipython==7.21.0
  - face-alignment==1.3.4
  - tensorflow-gpu==2.5.0
  - dlib
